<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-LBNBJ24" name="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta" tests="5" failures="0" timestamp="18 mar 2019 02:56:13 GMT" time="7.933" errors="1">
  <testcase name="dado_um_cliente_quando_o_cliente_adicionar_um_novo_planeta_entao_retorna_o_novo_planeta" time="7.932" classname="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta"/>
  <testcase name="dado_um_cliente_quando_o_cliente_consultar_todos_os_planetas_entao_retorna_a_listagem_de_planetas" time="0.000" classname="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta">
    <skipped/>
  </testcase> <!-- dado_um_cliente_quando_o_cliente_consultar_todos_os_planetas_entao_retorna_a_listagem_de_planetas -->
  <testcase name="dado_um_cliente_quando_o_cliente_adicionar_um_planeta_invalido_entao_retorna_erros" time="0.000" classname="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta">
    <skipped/>
  </testcase> <!-- dado_um_cliente_quando_o_cliente_adicionar_um_planeta_invalido_entao_retorna_erros -->
  <testcase name="iniciarBancoDeDados" time="0.001" classname="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta">
    <error type="com.wix.mysql.exceptions.CommandFailedException" message="Command &#039;&quot;CREATE DATABASE `test_database` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;&quot;&#039; on schema &#039;information_schema&#039; failed with message &#039;Cannot run program &quot;C:\Users\Carlos Kafka\Desktop\amedigital-desafio-tecnico\planetstarwars-server\target\mysql-5.7-d15a16d9-e4e8-4eaa-9bca-d1e710990ad7\bin\mysql&quot;: CreateProcess error=2, O sistema n達o pode encontrar o arquivo especificado&#039;">
      <![CDATA[com.wix.mysql.exceptions.CommandFailedException: Command '"CREATE DATABASE `test_database` CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;"' on schema 'information_schema' failed with message 'Cannot run program "C:\Users\Carlos Kafka\Desktop\amedigital-desafio-tecnico\planetstarwars-server\target\mysql-5.7-d15a16d9-e4e8-4eaa-9bca-d1e710990ad7\bin\mysql": CreateProcess error=2, O sistema n達o pode encontrar o arquivo especificado'
at com.wix.mysql.MysqlClient.execute(MysqlClient.java:80)
at com.wix.mysql.MysqlClient.executeCommands(MysqlClient.java:49)
at com.wix.mysql.EmbeddedMysql.addSchema(EmbeddedMysql.java:88)
at br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta.iniciarBancoDeDados(TestesControladorPlaneta.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: Cannot run program "C:\Users\Carlos Kafka\Desktop\amedigital-desafio-tecnico\planetstarwars-server\target\mysql-5.7-d15a16d9-e4e8-4eaa-9bca-d1e710990ad7\bin\mysql": CreateProcess error=2, O sistema n達o pode encontrar o arquivo especificado
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
at com.wix.mysql.MysqlClient.execute(MysqlClient.java:64)
... 31 more
Caused by: java.io.IOException: CreateProcess error=2, O sistema n達o pode encontrar o arquivo especificado
at java.lang.ProcessImpl.create(Native Method)
at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
at java.lang.ProcessImpl.start(ProcessImpl.java:137)
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
... 32 more
]]>
    </error>
  </testcase> <!-- iniciarBancoDeDados -->
  <testcase name="dado_um_cliente_quando_o_cliente_consultar_todos_os_planetas_entao_retorna_a_listagem_vazia_de_planetas" time="0.000" classname="br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta">
    <skipped/>
  </testcase> <!-- dado_um_cliente_quando_o_cliente_consultar_todos_os_planetas_entao_retorna_a_listagem_vazia_de_planetas -->
</testsuite> <!-- br.carloskafka.planetstarwars.controladores.TestesControladorPlaneta -->
